name: Python Application Bot

on:
  push:
    branches: [ "main" ] # Ou 'master', dependendo do nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9" # Ajuste para a versão que você usa
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # O "caminho" aqui é relativo à raiz do repositório
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run app.py
      run: |
        # Aqui o ambiente já tem os requisitos instalados
        python app.py
